title: Datapipes
description: Simple guides to help you go from zero data to serial dataset creator.
remote_theme: pages-themes/slate@v0.2.0
baseurl: "/datapipes" # Omit if site is at root
url: "https://patrickfleith.github.io" # Your GitHub Pages URL
