title: Datapipes
description: Simple guides to help you go from zero data to serial dataset creator.
theme: minimal
baseurl: "/datapipes" # Omit if site is at root
url: "https://patrickfleith.github.io" # Your GitHub Pages URL
